### ISSUE TITLE
Amazon Quicksight

### ISSUE THREAD

**Issue by gazoakley** [hashicorp/terraform-provider-aws#10990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have added support for managing Amazon Quicksight dashboards, data sources, etc through the API:

https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-quicksight-adds-api-support-for-data-dashboard-spice-and-permissions/ 

### New or Affected Resource(s)

- [X] `aws_quicksight_data_source` https://github.com/hashicorp/terraform-provider-aws/pull/21093
- [X] `aws_quicksight_group_membership` https://github.com/hashicorp/terraform-provider-aws/pull/20687
- [X] `aws_quicksight_group` https://github.com/hashicorp/terraform-provider-aws/pull/8233
- [X] `aws_quicksight_user` https://github.com/hashicorp/terraform-provider-aws/pull/10401
- [ ] `aws_quicksight_iam_policy_assignment` #11832

Depends on aws_quicksight_data_source:

- [ ] `aws_quicksight_data_set` #21101

Depends on aws_quicksight_data_set:

- [ ] `aws_quicksight_ingestion` #11833
- [ ] `aws_quicksight_template` #11834

Depends on aws_quicksight_template:

- [ ] `aws_quicksight_dashboard` #11835
- [ ] `aws_quicksight_template_alias` #11836

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.25.39](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.39):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10955

**Comment by bflad** [comment]
Hi @gazoakley 👋 Thanks for submitting this. Could you please split this into individual feature requests per resource? This will allow for easier concurrent work on the functionality and reduce confusion trying to understand the status of a single piece of functionality. Cheers!

**Comment by nwsparks** [comment]
Is there any api for managing the vpc connections?

**Comment by jeroenmeulendijks** [comment]
Is there any update on these issues? I see [#11831](https://github.com/hashicorp/terraform-provider-aws/issues/11831) being closed as there should be another issue, but I cannot find that issue.

I general I would like to know if this request is going to be picked up any time soon as we might benefit from it. If not I most likely will create something to support our needs.

**Comment by anGie44** [comment]
Hi all, please note that as of `v3.61.0` (upcoming) the checked-off resources in the description are present in the AWS provider. Since we have additional github issues that request the missing resources described above, I'm going to close this meta issue. Please refer to the additional quicksight resource github issues to track their progress.

**Comment by cwthrivent** [comment]
It appears the `github-actions` bot has marked some of the component issues relating to this one as Closed (e.g. #11833). Should those be re-opened for visibility?

**Comment by mmerickel** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/23083 belongs in this list as well.

**Comment by mmerickel** [comment]
Can https://github.com/hashicorp/terraform-provider-aws/issues/11833 get reopened?

**Comment by russ-s7** [comment]
> Is there any api for managing the vpc connections?

Can't see anything at https://docs.aws.amazon.com/quicksight/latest/APIReference/API_Operations.html

So I wouldn't expect an `aws_quicksight_vpc_connection` resource to be forthcoming any time soon.

**Comment by posquit0** [comment]
How about a new resource for QuickSight `create-folder-membership` API?

- https://docs.aws.amazon.com/quicksight/latest/developerguide/create-folder-membership.html

**Comment by seanlogan-wh** [comment]
Are there any plans to support creating an analysis as well?  We use those alongside templates and dashboards. 
https://docs.aws.amazon.com/quicksight/latest/developerguide/create-analysis.html

**Comment by comtef** [comment]
> Are there any plans to support CRUD operations on an analysis as well? We use those alongside templates and dashboards. https://docs.aws.amazon.com/quicksight/latest/developerguide/create-analysis.html

@seanlogan-wh I'll add it when template resource is merged.

**Comment by jar-b** [comment]
With the completion of the `aws_quicksight_dashboard` resource (forthcoming in `v5.1.0`), all of the original resources collected in this meta issue are now complete, and we'll be closing it as completed.

For any additional QuickSight resource or data source requests, please open a new issue. Thanks!
