### ISSUE TITLE
CI tooling to ensure documentation and acceptance tests use Terraform 0.12 syntax

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#14417]
Add CI tooling to ensure that all new documentation and acceptance test contributions use Terraform 0.12 syntax.

Was originally part of #8950.

**Comment by anGie44** [comment]
Data Source Testing Configurations Complete: 
- [x] A-E(bs Volumes) #14395 
- [x] E(c2) - E(fs Mount) #14399 
- [x] E(ip) - I(am Server) #14400 
- [x] I(am User) - K(ms Key) #14401 
- [x] L(ambda Alias) - M(sk Configuration) #14402
...
