### ISSUE TITLE
tests/provider: Various RDS cluster tests failing (GovCloud)

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#16029]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

These tests are successful (or ignored) in the commercial partition but fail in GovCloud:

#### InvalidParameterValue:

- [ ] TestAccAWSRDSCluster_BacktrackWindow (`Backtrack is not enabled for the aurora engine.`)
- [ ] TestAccAWSRDSCluster_ReplicationSourceIdentifier_KmsKeyId (`Read replica DB clusters are not available in this region for engine aurora`)
- [ ] TestAccAWSRDSCluster_EngineMode_Multimaster (`The engine mode multimaster you requested is currently unavailable.`)
- [ ] TestAccAWSRDSCluster_EnableHttpEndpoint (`The engine mode serverless you requested is currently unavailable.`)
- [ ] TestAccAWSRDSCluster_EngineMode (`The engine mode serverless you requested is currently unavailable.`)
- [ ] TestAccAWSRDSCluster_ScalingConfiguration (`The engine mode serverless you requested is currently unavailable.`)
- [ ] TestAccAWSRDSCluster_ScalingConfiguration_DefaultMinCapacity (`The engine mode serverless you requested is currently unavailable.`)
- [ ] TestAccAWSRDSCluster_EngineMode_ParallelQuery (`The requested engine version was not found or does not support parallelquery functionality`)
- [ ] TestAccAWSRDSCluster_SnapshotIdentifier_EngineMode_ParallelQuery (`The requested engine version was not found or does not support parallelquery functionality`)

#### InvalidParameterCombination

- [x] (#16038) TestAccAWSRDSCluster_EngineVersion (`Cannot find version 9.6.3 for aurora-postgresql`)
- [x] (#16038) TestAccAWSRDSCluster_EngineVersionWithPrimaryInstance (`Cannot find version 9.6.3 for aurora-postgresql`)
- [x] (#16038) TestAccAWSRDSCluster_SnapshotIdentifier_EngineVersion_Different (`Cannot find version 9.6.3 for aurora-postgresql`)
- [x] (#16038) TestAccAWSRDSCluster_SnapshotIdentifier_EngineVersion_Equal (`Cannot find version 9.6.3 for aurora-postgresql`)

### New or Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files

Example config:

```hcl
resource "aws_rds_cluster" "test" {
  apply_immediately         = true
  backtrack_window          = 43200
  cluster_identifier_prefix = "tf-acc-test-"
  master_password           = "mustbeeightcharaters"
  master_username           = "test"
  skip_final_snapshot       = true
}
```

### Debug Output

```
Error: error creating RDS cluster: InvalidParameterValue: Backtrack is not enabled for the aurora engine.
Error: error creating RDS cluster: InvalidParameterValue: Read replica DB clusters are not available in this region for engine aurora
Error: error creating RDS cluster: InvalidParameterValue: The engine mode multimaster you requested is currently unavailable.
Error: error creating RDS cluster: InvalidParameterValue: The engine mode serverless you requested is currently unavailable.
Error: error creating RDS cluster: InvalidParameterValue: The requested engine version was not found or does not support parallelquery functionality

Error: error creating RDS cluster: InvalidParameterCombination: Cannot find version 9.6.3 for aurora-postgresql
```

### References

* hashicorp/terraform-plugin-sdk#592
