### ISSUE TITLE
tests/provider:  Your query returned no results.

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#16226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Several tests fails on GovCloud (and some on commercial also):

- [x] TestAccAwsAutoScalingGroupDataSource_basic (comm/GovCloud) (#16225)
- [x] TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces (#16225)
- [x] TestAccAWSInstance_noAMIEphemeralDevices (#16229)
- [x] TestAccAWSInstancesDataSource_basic (#16229)
- [x] TestAccAWSInstancesDataSource_instance_state_names (#16229)
- [x] TestAccAWSInstancesDataSource_tags (#16229)
- [x] TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS (#16254)
- [x] TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination (#16254)
- [x] TestAccAWSSSMAssociation_withAutomationTargetParamName (#16254)
- [x] TestAccAWSSSMDocument_automation (#16254)
- [x] TestAccAWSSSMDocument_package (#16254)

With this error: `Error: Your query returned no results. Please change your search criteria and try again.`.

### New or Affected Resource(s)

* data/aws_autoscaling_group
* aws_ec2_fleet
* aws_instance
* data/aws_instance
* aws_launch_template
* aws_ssm_association
* aws_ssm_document

### Terraform Configuration Files

Example config:

```hcl
data "aws_autoscaling_group" "good_match" {
  name = aws_autoscaling_group.foo.name
}
```

### Debug Output

```
Error running pre-apply refresh:
        
Error: Your query returned no results. Please change your search criteria and try again.
```

### References

* #16225 
* #16229 
* #16254
