### ISSUE TITLE
tests: Remove deprecated type constraints

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#17920]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Terraform 0.11 and earlier required type constraints to be given in quotes,
        but that form is now deprecated and will be removed in a future version of
        Terraform. Remove the quotes around "list" and write list(string) instead to
        explicitly indicate that the list elements are strings.

### Affected Tests

- [x] TestAccAWSCloudHsmV2Cluster_Tags (#17921)
- [x] TestAccAWSCloudHsmV2Cluster_basic (#17921)
- [x] TestAccAWSLBListenerRule_BackwardsCompatibility (#17922)
- [x] TestAccAWSLBListenerRule_basic (#17922)
- [x] TestAccAWSLBListenerRule_changeListenerRuleArnForcesNew (#17922)
- [x] TestAccAWSLBListenerRule_cognito (#17922)
- [x] TestAccAWSLBListenerRule_conditionHostHeader (#17922)
- [x] TestAccAWSLBListenerRule_conditionHttpHeader (#17922)
- [x] TestAccAWSLBListenerRule_conditionHttpRequestMethod (#17922)
- [x] TestAccAWSLBListenerRule_conditionMultiple (#17922)
- [x] TestAccAWSLBListenerRule_conditionPathPattern (#17922)
- [x] TestAccAWSLBListenerRule_conditionQueryString (#17922)
- [x] TestAccAWSLBListenerRule_conditionSourceIp (#17922)
- [x] TestAccAWSLBListenerRule_conditionUpdateMixed (#17922)
- [x] TestAccAWSLBListenerRule_conditionUpdateMultiple (#17922)
- [x] TestAccAWSLBListenerRule_fixedResponse (#17922)
- [x] TestAccAWSLBListenerRule_forwardWeighted (#17922)
- [x] TestAccAWSLBListenerRule_oidc (#17922)
- [x] TestAccAWSLBListenerRule_priority (#17922)
- [x] TestAccAWSLBListenerRule_redirect (#17922)
- [x] TestAccAWSLBListenerRule_updateFixedResponse (#17922)
- [x] TestAccAWSLBListenerRule_updateRulePriority (#17922)
- [x] TestAccAWSLBListener_BackwardsCompatibility (#17928)
- [x] TestAccAWSLBListener_basic (#17928)
- [x] TestAccAWSLBListener_basicUdp (#17928)
- [x] TestAccAWSLBListener_cognito (#17928)
- [x] TestAccAWSLBListener_fixedResponse (#17928)
- [x] TestAccAWSLBListener_forwardWeighted (#17928)
- [x] TestAccAWSLBListener_https (#17928)
- [x] TestAccAWSLBListener_oidc (#17928)
- [x] TestAccAWSLBListener_redirect (#17928)
- [x] TestAccAWSLB_ALB_basic (#17930)
- [x] TestAccAWSLB_BackwardsCompatibility (#17930)
- [x] TestAccAWSLB_applicationLoadBalancer_updateDeletionProtection (#17930)
- [x] TestAccAWSLB_applicationLoadBalancer_updateDropInvalidHeaderFields (#17930)
- [x] TestAccAWSLB_applicationLoadBalancer_updateHttp2 (#17930)
- [x] TestAccAWSLB_generatedName (#17930)
- [x] TestAccAWSLB_generatesNameForZeroValue (#17930)
- [x] TestAccAWSLB_namePrefix (#17930)
- [x] TestAccAWSLB_noSecurityGroup (#17930)
- [x] TestAccAWSLB_tags (#17930)
- [x] TestAccAWSLB_updatedSecurityGroups (#17930)
- [x] TestAccAWSLB_updatedSubnets (#17930)
- [x] TestAccAWSShieldProtection_Alb (#17931)
- [x] TestAccAWSShieldProtection_Elb (#17931)
- [ ] TestAccDataSourceAWSALBTargetGroup_basic (#17932)
- [ ] TestAccDataSourceAWSELB_basic (#17932)
- [ ] TestAccDataSourceAWSLBListener_BackwardsCompatibility (#17932)
- [ ] TestAccDataSourceAWSLBListener_basic (#17932)
- [ ] TestAccDataSourceAWSLBListener_https (#17932)
- [ ] TestAccDataSourceAWSLBTargetGroup_BackwardsCompatibility (#17932)
- [ ] TestAccDataSourceAWSLB_BackwardsCompatibility (#17932)
- [ ] TestAccDataSourceAWSLB_basic (#17932)
- [x] TestAccDataSourceCloudHsmV2Cluster_basic (#17921)

### References

* #0000
