### ISSUE TITLE
Add AWS Audit Manager support

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#17981]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Audit Manager helps you continuously audit your AWS usage to simplify how you assess risk and compliance with regulations and industry standards. Audit Manager automates evidence collection to reduce the “all hands on deck” manual effort that often happens for audits and enable you to scale your audit capability in the cloud as your business grows. With Audit Manager, it is easy to assess if your policies, procedures, and activities – also known as controls – are operating effectively. When it is time for an audit, AWS Audit Manager helps you manage stakeholder reviews of your controls and enables you to build audit-ready reports with much less manual effort.

> AWS Audit Manager’s prebuilt frameworks help translate evidence from cloud services into auditor-friendly reports by mapping your AWS resources to the requirements in industry standards or regulations, such as CIS AWS Foundations Benchmark, the General Data Protection Regulation (GDPR), and the Payment Card Industry Data Security Standard (PCI DSS). You can also fully customize a framework and its controls for your unique business requirements. Based on the framework you select, Audit Manager launches an assessment that continuously collects and organizes relevant evidence from your AWS accounts and resources, such as resource configuration snapshots, user activity, and compliance check results.

> You can get started quickly in the AWS Management Console. Just select a prebuilt framework to launch an assessment and begin automatically collecting and organizing evidence.

### New or Affected Resource(s)

May require several new resources and data sources.

### Definition of Done for This Issue

- [x] Add Audit Manager service client #18071 #27818
- [x] Add Audit Manager resources
  - [x] `aws_auditmanager_control` #27857 
  - [x] `aws_auditmanager_framework` #28257
  - [x] `aws_auditmanager_framework_share` #29049
  - [x] `aws_auditmanager_assessment` #28643 
  - [x] `aws_auditmanager_assessment_report` #28663 
  - [x] `aws_auditmanager_assessment_delegation` #29099
  - [x] `aws_auditmanager_account_registration` #28314
  - [x] `aws_auditmanager_organization_admin_account_registration` #29018
- [x] Add Audit Manager data sources
  - [x] `aws_auditmanager_control` #28967
  - [x] `aws_auditmanager_framework` #28989

### References

* https://aws.amazon.com/audit-manager/
* https://docs.aws.amazon.com/sdk-for-go/api/service/auditmanager/

**Comment by drarnold** [comment]
Heyo @YakDriver & @breathingdust 
I was going to work on a Pull Request to handle `Add Initial Audit Manager Resource` portion of this issue.  I won't promise that I'll get something out, but I am going to give it my best effort.  I'll reach out if I can't get it done.

Thanks!

**Comment by michal-kosinski** [comment]
Hello @drarnold any updates on this one? Thank you!

**Comment by drarnold** [comment]
Hey @michal-kosinski 
I was re-allocated to different projects and won't be able to contribute to this issue in the foreseeable future.  Maybe if someone else could take an attempt at getting this implemented.

Thanks

**Comment by adv4000** [comment]
2nd June 2022, still not update :(

**Comment by adv4000** [comment]
Some workaround to enable Audit Manager and Delegate Admin to another account:
```
# Enable Audit Manager on ROOT/Management account
resource "null_resource" "enable_on_mgmt" {
  provisioner "local-exec" {
    command = "aws auditmanager register-account"
  }
}

# Delegate Audit Manager Admin to account 77777777777
resource "null_resource" "delegata_to_admin" {
  provisioner "local-exec" {
    command = "aws auditmanager register-organization-admin-account --admin-account-id 77777777777"
  }
  depends_on = [null_resource.enable_on_mgmt]
}

```

**Comment by jar-b** [comment]
All planned resources and data sources have now been implemented.

Please open a new issue for any feature requests, bugs, or additional resources/data sources as new API's become available.
