### ISSUE TITLE
Realign inconsistent resource/data source names (without miffing community)

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#19999]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* We should rename resources that include service names which are inconsistent with the rest of the provider.
* To avoid miffing practitioners with breaking changes, we should alias the renamed resources to their pre-rename names.

### Service Name Rules

The vast majority of the time, the lowercase, no-spaces service name we use in the provider is identical to the AWS Go SDK package name (_e.g._, `ec2` = `ec2`). However, we have diverged from the AWS Go SDK in the past for good reason. On occasion, the AWS name is not consistent with other AWS names. Sometimes the AWS names are very long. 

In the future, we will diverge from AWS Go SDK names but we should be consistent in how we do so.

#### Provider Service Package Names Rule

The provider service package name should be the same as the AWS Go SDK package name except:

* Drop "service" or "api" if the service name ends with either or both, and
* Shorten the service name if it is excessively long. Avoid names longer than 17 characters if possible. When shortening a service name, look to the endpoints ID, common usage in documentation and marketing, and discuss the change with the community and maintainers to get buy in. The goals for this alternate name are to be instantly recognizable, not verbose, and more easily managed.
* Examples of proper provider service package names include `ec2` (identical to AWS Go SDK package), `prometheus` ("service" dropped), and `serverlessapprepo` (shortened from `serverlessapplicationrepository`).

#### Resource & Data Source Names

Resources and data sources should follow this naming scheme:
```
aws_{providerservicepackagename}_{thing}
```

The provider service package name should:
* _NOT_ include underscores ("_") (_e.g._, `aws_api_gateway_authorizer` should be `aws_apigateway_authorizer`)

### Why?

Why rename a bunch of data source and resources?

1. We should do this now because this is a once in a 5-10 year opportunity. We currently have many broken PRs. That is unfortunate but also an opportunity.
2. Removing sloppiness, i.e., inconsistency, projects a professional image.
5. We can make the change without miffing practitioners because we'll provide aliases they can continue to use seamlessly. Practitioners that want their configurations to look neater, with clean resource names, can use the new names. Brand new practitioners will only ever know consistency.
7. Even if Terraform core does not allow switching resource types with `move`, no practitioners _need_ to move. They can continue using aliases as always. For those that _want_ to use the renamed resources (rather than the aliases), only those with long-term resources will be negatively affected, which is mitigated by using `import`. For practitioners with more ephemeral resources, after `destroy` they can `apply` using the newly renamed resources.
6. Although there is extra maintenance in having resource aliases, the burden with existing ELB aliases has been light.
3. The consistency standards we maintain influence what contributors view as acceptable work. Contributors submitting higher standard work reduces the portion of our workload dedicated to clean up.
4. Contributors pick existing work as examples of what to do. If there's only one way we do things, contributors will always pick a good example. If we provide bad examples, we should not be surprised to get inconsistent contributions.
4. As we create _new_ resources in services with bad resource naming, we are perpetuating the problem. A fix now will allow new resources from this point forward in these services to not further contribute to the problem

**NOTE:** Due to history, size, and frequency of use, we should give `ec2` and `meta` pragmatic exceptions.
 
### New or Affected Resource(s)

- [ ] aws_alb* (#21594)
- [ ] aws_api_gateway_* (#21570)
- [ ] aws_app_cookie_stickiness_policy (#21593)
- [ ] aws_caller_identity (#21568)
- [ ] aws_canonical_user_id (#21569)
- [ ] aws_cloudcontrolapi_* (#21572)
- [ ] aws_cloudhsm_v2_* (#21585)
- [ ] aws_cloudwatch_event_* (#21586)
- [ ] aws_cloudwatch_log_* (#21587)
- [ ] aws_cloudwatch_query_definition (#21587)
- [ ] aws_cognito_* (#21589)
- [ ] aws_directory_service_* (#21590)
- [ ] aws_dx_* (#21591)
- [ ] aws_elastic_beanstalk_* (#21592)
- [ ] aws_kinesis_firehose_* (#21596)
- [ ] aws_kinessis_analytics_* (#21599)
- [ ] aws_kinessis_video_* (#21600)
- [ ] aws_launch_configuration (#21571)
- [ ] aws_lb_cookie_stickiness_policy (#21593)
- [ ] aws_lb_ssl_negotiation_policy (#21593)
- [ ] aws_lb* (#21593, #21594)
- [ ] aws_lex_* (#21552)
- [ ] aws_load_balancer_* (#21593)
- [ ] aws_media_convert_* (#21601)
- [ ] aws_media_package_* (#21602)
- [ ] aws_media_store_* (#21603)
- [ ] aws_msk_* (#21598)
- [ ] aws_proxy_protocol_policy (#21593)
- [ ] aws_resourcegroupstaggingapi_resources (#21604)
- [ ] aws_route53_resolver_* (#21605)
- [ ] aws_s3_access* (#21606)
- [ ] aws_s3_account* (#21606)
- [ ] aws_service_discovery_* (#21607)

### References

* #0000

**Comment by YakDriver** [comment]
Let's prioritize aligning these resources, as it's essential to maintain a polished and consistent experience. Using an outdated name like `aws_cloudwatch_event_bus` doesn't just look shoddy—it can also lead to confusion for practitioners navigating AWS documentation and the console. By updating the resource name to match the current terminology used by AWS, we ensure clarity and professionalism across our infrastructure.

The approach used by other providers is to create a new resource with the correct name and deprecate the old resource with the wrong name. When the major version arrives, they dispatch the old resource.
