### ISSUE TITLE
resource/aws_opsworks_stack: Acctest `TestAccOpsWorksStack_classicEndpoints` uses non-standard multi-region method

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#21887]
The AWS OpsWorks service supports regional endpoints as well as legacy "classic" endpoints (https://github.com/aws/aws-sdk-go/blob/35b0995ae20b813c40e7808b87f6e922bc6ab212/service/opsworks/api.go#L9259-L9276)

To test the classic endpoint, the acceptance test `TestAccOpsWorksStack_classicEndpoints` directly configures provider blocks with a `region` parameter. This method is discouraged (https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/running-and-writing-acceptance-tests.md#hardcoded-region).

The test cannot currently be run in parallel with other tests, because of how it manipulates the global `acctest.Providers` value.

### Affected Resource

* aws_opsworks_stack

### Tasks

- [ ] Create a custom `ConfigOpsWorksClassicEndpointProvider()` similar to `ConfigEC2ClassicRegionProvider()`
- [ ] Allow the test to be run from any of the supported classic regions, not just `us-west-2`
- [ ] Update the test to use `ProviderFactories: acctest.ProviderFactories` instead of `Providers: acctest.Providers`

### Reference

Discovered while working on #20221
