### ISSUE TITLE
[Tracking Issue] Order is lost in JSON/policies when applied

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#21968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Relates #22048 

### Centralized JSON List/Array Diff Issue

When Terraform reports a spurious diff, it can be inconvenient. If that non-diff forces replacement, it can seriously affect systems. _We don't want that._

This issue focues on **_AWS provider non-diffs occurring on AWS policy JSONs_**. It is looking at the problem, tracking fixes, and gathering references.

### Diffs vs. Reordering vs. Preserving Order vs. Ignoring Order

Assuming that non-diff diffs (i.e., spurious diffs) are the crux of the problem, consistent reordering (such as alphabetical or anti-alphabetical as with #6107), preserving the given order, or completely ignoring order within JSON arrays can all be solutions. Many times issues suggest some variation of ordering but the bottom-line reason seems to be avoiding diffs.

### Step 1

In this round of fixes, the approach is to ignore order by only setting a new policy JSON when it is not equivalent to the existing policy JSON. The data source `aws_iam_policy_document` takes a different approach by reordering the JSON arrays, currently anti-alphabetically (see #6107).

### Companion Issue to #11801 

Perhaps the most popular issue to describe these problems is #11801. Rather than hijack it, this is a generalized issue and central place for documenting similar problems and tracking fixes.

### Fixes Needed

- [x] apigateway/rest_api (#22115)
- [x] apigateway/rest_api_policy (#22115)
- [x] apigatewayv2/model (verified non-policy JSON)
- [x] appconfig/configuration_profile (verified non-policy JSON)
- [x] backup/vault_policy (#22130)
- [x] cloudwatch/dashboard (verified non-policy JSON)
- [x] cloudwatchlogs/resource_policy (#22135)
- [x] codeartifact/domain_permissions_policy (#22136)
- [x] codeartifact/repository_permissions_policy (#22136)
- [x] codecommit/approval_rule_template (verified non-policy JSON)
- [x] configservice/organization_custom_rule (verified non-policy JSON)
- [x] configservice/organization_managed_rule (verified non-policy JSON)
- [x] connect/contact_flow (verified non-policy JSON)
- [x] dms/replication_task (verified non-policy JSON)
- [x] ec2/vpc_endpoint (#22137)
- [x] ecr/lifecycle_policy (#22142)
- [x] ecr/registry_policy (#22004)
- [x] ecr/repository_policy (#22004)
- [x] efs/file_system_policy (#22100)
- [x] elasticsearch/domain (#22157)
- [x] elasticsearch/domain_policy (#22157)
- [x] emr/cluster (verified non-policy JSON)
- [x] emr/instance_group (verified non-policy JSON)
- [x] events/bus_policy (#22165)
- [x] fms/policy (verified non-policy JSON)
- [x] glacier/vault (#22166)
- [x] glacier/vault_lock (#22166)
- [x] glue/crawler (verified non-policy JSON)
- [x] glue/resource_policy (#22167)
- [x] iam/group_policy (#22067)
- [x] iam/policy (#22067)
- [x] iam/role (#22099)
- [x] iam/role_policy (#22067)
- [x] iam/user_policy (#22067)
- [x] iot/policy (#22169)
- [x] kms/external_key (#21990)
- [x] kms/key (#21969)
- [x] kms/replica_external_key (#21990)
- [x] kms/replica_key (#21990)
- [x] lambda/invocation_data_source_test (verified non-policy JSON)
- [x] mediastore/container_policy (#22170)
- [x] networkfirewall/resource_policy (#22171)
- [x] opsworks/stack (verified non-policy JSON)
- [x] organizations/policy (verified non-IAM-policy JSON)
- [x] s3/bucket (#21997)
- [x] s3/bucket_policy (#21997)
- [x] s3control/access_point (#22255)
- [x] s3control/access_point_policy (#22255)
- [x] s3control/bucket_policy (#22255)
- [x] s3control/multi_region_access_point_policy (#22255)
- [x] s3control/object_lambda_access_point_policy (#22255)
- [x] sagemaker/flow_definition (verified non-policy JSON)
- [ ] sagemaker/model_package_group_policy (#22259)
- [x] schemas/schema (verified non-policy JSON)
- [x] secretsmanager/secret (#22217)
- [x] secretsmanager/secret_policy (#22217)
- [x] servicecatalog/constraint (verified non-policy JSON)
- [x] servicecatalog/diff (verified non-policy JSON)
- [x] ses/identity_policy (#22214)
- [x] sns/topic (#22213)
- [x] sns/topic_policy (#22213)
- [x] sns/topic_subscription (verified non-IAM-policy JSON)
- [x] sqs/queue (#22194)
- [x] sqs/queue_policy (#22194)
- [x] ssoadmin/permission_set_inline_policy (#22192)
- [x] transfer/access (#22193)
- [x] transfer/user (#22193)

#### Provider References
* #6107
* #11801
* #13144
* #17024
* #18878
* #19245
* #19365
* #19444
* #19627
* #20107
* #20456
* #20665
* #20781

#### Other References
* hashicorp/awspolicyequivalence#1
* hashicorp/awspolicyequivalence#7
* https://github.com/hashicorp/awspolicyequivalence
* hashicorp/terraform-plugin-framework#70
* hashicorp/terraform-plugin-sdk#801
* jen20/awspolicyequivalence#10
* hashicorp/terraform#22931
* hashicorp/terraform#27880
* hashicorp/terraform#28803
* hashicorp/terraform#29685
