### ISSUE TITLE
[Umbrella] ISO-friendly Tagging

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#22532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Relates #18593

## Considerations

Five (at least) considerations relate to the problem of tagging support in non-standard AWS partitions:
* Tag on Create - When this is available, it's highly desireable. I.e., we want to prioritize its use.
* Tagging support (at all) - Not working at all contrasts with not supporting tag on create.
* Default tags - Ideally, practitioners will be able to use default tags even if not all resources in non-standard partitions support tagging.
* Changing AWS functionality - Ideally, we will not need to change the code when AWS adds levels of tagging support to other partitions. Features will simply start working.
* Avoid eating errors that should be fatal - Eventual consistency or actual tagging problems should result in errors reported to practitioners. Thus the challenge is to narrowly eat errors that specifically relate to lack of tagging support.

## Design

A design to handle these considerations:

### Tag on Create

Attempt tag on create

| Tags? | DTags? | Error? | Result |
| --- | --- | --- | --- |
| 0 | 0 | 0 | 👍 |
| 0 | 0 | 1 | Don't ToC if `len(tags) == 0` |
| 0 | 1 | 0 | 👍 |
| 0 | 1 | 1 | Attempt post-create tag |
| 1 | 0 | 0 | 👍 |
| 1 | 0 | 1 | Attempt post-create tag |
| 1 | 1 | 0 | 👍 |
| 1 | 1 | 1 | Attempt post-create tag |

### Tag after Create

Only if tag on create fails, check error and, if appropriate, try create without tags.

| Tags? | DTags? | Error? | Result |
| --- | --- | --- | --- |
| 0 | 1 | 0 | 👍 |
| 0 | 1 | 1 | Log error, continue |
| 1 | 0 | 0 | 👍 |
| 1 | 0 | 1 | Fatal error (explicit setting of tags when tagging not possible) |
| 1 | 1 | 0 | 👍 |
| 1 | 1 | 1 | Fatal error (explicit setting of tags when tagging not possible) |

### Read

1. Attempt to read tags
2. If tag read fails, check error and, if appropriate, skip tag read.

| Tags? | DTags? | Error? | Result |
| --- | --- | --- | --- |
| 0 | 0 | 0 | 👍 |
| 0 | 0 | 1 | Regular, non-tag error |
| 0 | 1 | 0 | 👍 |
| 0 | 1 | 1 | Log error, continue |

### Update

1. Attempt tag update
2. If update fails, check error and, if appropriate, skip tag update.

| Tags? | DTags? | Error? | Result |
| --- | --- | --- | --- |
| 0 | 0 | 0 | 👍 |
| 0 | 0 | 1 | Regular, non-tag error |
| 0 | 1 | 0 | 👍 |
| 0 | 1 | 1 | Log error, continue |

### New or Affected Resource(s)

- [x] ds/aws_ecr_repository (#22535)
- [x] ds/aws_iam_role (#22544)
- [x] ds/aws_iam_user (#22544)
- [x] ds/aws_lb (#22551)
- [x] ds/aws_lb_listener (#22551)
- [x] ds/aws_lb_target_group (#22551)
- [x] ds/aws_sqs_queue (#22516)
- [x] r/aws_cloudwatch_event_rule (#22550)
- [x] r/aws_cloudwatch_event_bus (#22550)
- [x] r/aws_cloudwatch_composite_alarm (#22556)
- [x] r/aws_cloudwatch_metric_alarm (#22556)
- [x] r/aws_cloudwatch_metric_stream (#22556)
- [x] r/aws_ecr_repository (#22535)
- [x] r/aws_ecs_capacity_provider (#22529)
- [x] r/aws_ecs_cluster (#22529)
- [x] r/aws_ecs_service (#22529)
- [x] r/aws_ecs_task_definition (#22529)
- [x] r/aws_ecs_task_set (#22529)
- [x] r/aws_iam_group (no tags)
- [x] r/aws_iam_role (#22544)
- [x] r/aws_iam_user (#22544)
- [x] r/aws_lb (#22551)
- [x] r/aws_lb_listener (#22551)
- [x] r/aws_lb_listener_rule (#22551)
- [x] r/aws_lb_target_group (#22551)
- [x] r/aws_sns_topic (#22511)
- [x] r/aws_sqs_queue (#22516)

### References

* #18593

**Comment by blafrisch** [comment]
`aws_cloudwatch_event_rule` and `aws_lb_listener` are additional resources that we know of to have tagging issues in the ISO regions.

**Comment by YakDriver** [comment]
@blafrisch @lorengordon We're doing our best to anticipate the errors but since they often vary from service to service, we are not 100% confident these fixes will guard against the exact errors for all these services. This is attempt #1. 🤞 

Now with the guard structure in place, updating for the correct error is pretty trivial. But, as we cannot test ourselves, any help with that would be much appreciated. The error code and message would be ideal.

Here are the error codes that v3.72.0 will be guarding against:

ECR:
* AccessDenied
* InvalidParameter
* Validation

ECS:
* AccessDenied
* InvalidParameter
* UnsupportedFeature

SNS:
* AccessDenied
* AuthorizationError
* InvalidAction

SQS:
* AccessDenied
* AuthorizationError
* InvalidAction
* UnsupportedOperation

**Comment by egon010** [comment]
Is there a test suite yet to gather results from various partitions/regions?

**Comment by YakDriver** [comment]
Yes and no. Formally, we only run daily tests across `aws` (standard partition) and `aws-us-gov` (GovCloud), and mostly `us-west-2` and `us-gov-west-1`. We track those results. We don't have access to iso regions in house. There are some similarities between the China and iso partitions. We don't have information from AWS on whether they are the same but that could be a potential avenue for testing.

**Comment by lorengordon** [comment]
We'll give it a go, thanks for the heads up!

**Comment by blafrisch** [comment]
@YakDriver we were able to deploy v3.72.0 and test with the `aws_cloudwatch_event_rule` and `aws_lb_listener` resources; both still experienced errors. Note that these messages are hand-transcribed and have some info redacted:

For `aws_cloudwatch_event_rule`:
```
Error: error listing tags for EventBridge Rule (arn:aws-iso:events:<REDACTED>:rule/<REDACTED>): UnknownOperationException Operation is disabled in this region
status code: 400
```

For `aws_lb_listener`: 
```
Error: error listing tags for (arn:aws-iso:elasticloadbalancing:<REDACTED>:listener/<REDACTED>): ValidationError: Resource type 'listener' does not support tagging
status code: 400
```

**Comment by spavuluri** [comment]
@YakDriver can confirm the same error with v3.72.0 in aws-iso.

In the console, the resource appears like its created, at least in the case of cloudwatch event rule. But the `apply` reports above error.

Testing continues.

**Comment by YakDriver** [comment]
- [ ] CloudWatch
- [ ] ECR
- [ ] ECS
- [ ] ELBv2
- [ ] EventBridge (CloudWatch Events)
- [ ] IAM
- [x] SNS
- [ ] SQS

**Comment by blafrisch** [comment]
@YakDriver I can confirm that the most recent changes were successful in `aws-iso` for `aws_cloudwatch_event_rule` and `aws_lb_listener`. 🎉

**Comment by spavuluri** [comment]
@YakDriver no issues encountered for `aws_sqs_queue`, `aws_sns_topic`, `aws_cloudwatch_metric_alarm`, `aws_ecr_repository` in `aws-iso`

**Comment by YakDriver** [comment]
@spavuluri @blafrisch Millions of thanks!!

We have heard back that ECS continues to be a problem but still need to find out what the exact error message is. If anyone has the AWS error code (e.g., `UnknownOperationException`) and message, that would be super helpful! Once we have that, we can get a fix out quickly.

**Comment by YakDriver** [comment]
ECS handles tagging differently than (most?) every other service. As a result, it took a different approach than the others but hopefully it should be working now with #23030. If we don't hear back for anyone in the next 30 days on more tagging problems in ISO, I'll close this issue on or after March 8, 2022. Thanks for all the help!

**Comment by lorengordon** [comment]
@YakDriver I see the PR fixing ECS tags was marked for the v4 release... Does that mean it won't make it into a v3 release?

**Comment by YakDriver** [comment]
That is likely correct. Any estimate of showstoppers with v4 and ISO?

**Comment by lorengordon** [comment]
Just makes it harder to test, is all, with all the breaking changes. Folks might need some time to rewrite configs to account for that, before they can report that things are or are not working.

**Comment by caleb-devops** [comment]
@YakDriver v3.74.0 did fix most of the errors relating to tagging, however I am receiving the following error during terraform apply for `aws_iam_instance_profile` resources:

```
error updating tags for IAM Instance Profile (<REDACTED>): Error tagging resource (<REDACTED>): InvalidAction: Unsupported operation.
```

**Comment by YakDriver** [comment]
The ECS fixes have been backported to v3.74 and are available in v3.74.3.

**Comment by AbrohamLincoln** [comment]
I ran into this this today with the following resources:
aws_elasticache_subnet_group
aws_elasticache_replication_group

**Comment by YakDriver** [comment]
@AbrohamLincoln Thank you for letting us know. We'll work on a fix.

**Comment by YakDriver** [comment]
@AbrohamLincoln For ElastiCache fixes, see #23980. When 4.9 is released (next week I believe), please give it a test and let us know if it works. We are unable to test in `iso` or `iso-b` on our own.
