### ISSUE TITLE
Contributor Documentation Review and Restructure

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#25600]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Effective contributor documentation is essential to allow new contributors to orient themselves, and for seasoned contributors to use as a reference. These two contributor types have slightly different requirements when it comes to documentation. The current AWS provider documentation leans more towards the reference model, and we have heard feedback from users that while the documentation is comprehensive, it is intimidating for new users and hard to navigate.

To help new contributors get started, and to allow existing contributors to find the reference they need more quickly we should restructure the documentation to allow a workflow based landing page, which details the steps required to accomplish a task at a high level. These workflows can link out to reference documents for more detailed information. 

A navigation structure to allow 2nd/3rd level navigation would help users find the information they need much more easily. The existing GitHub UI doesn't allow for this, but moving towards a documentation microsite hosted on GitHub Pages would allow this.

### Tasks

- [x] Enable GitHub pages and select static site generator / template
- [x] Create landing/workflow page
- [x] Break up massive checklist pages into task related sections.
- [x] General review/refactor
- [ ] Add aws-go-sdk 1 vs 2 section
- [ ] Add aws-go-sdk-base section
- [ ] Make decision on skaff, as it is sdk v2 oriented, we need to be comfortable recommending its use for new users.
- [ ] Ensure issue / PR template information aligns with revamped documentation
