### ISSUE TITLE
[Provider]: Migration to aws-sdk-go-v2

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#32976]
### Description

The majority of the Terraform AWS Providers resources and data sources are based on [aws-sdk-go](https://github.com/aws/aws-sdk-go). Currently we support the use of both [aws-sdk-go](https://github.com/aws/aws-sdk-go) and [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2) in the provider, and have a significant number of resources based on [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2). 

AWS have now [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/) the End-Of-Support plan for the AWS SDK for Go v1 which presents these key dates for the provider to work towards:

**Start of Maintenance Mode: July 31, 2024**

Effectively this means that feature development on existing resources will require migration to v2 of the provider, as new features will not be added to that version of the SDK.

**End of Support: July 31, 2025**

By this time the provider should not have any functionality dependent on V1 of the SDK.

The maintainer team has [stopped](https://github.com/hashicorp/terraform-provider-aws/issues/32917) accepting net-new resources/data sources based on [aws-sdk-go](https://github.com/aws/aws-sdk-go).

### References

- #32917
- [Announcing end-of-support for AWS SDK for Go (v1) effective July 31, 2025](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/)
- https://aws.github.io/aws-sdk-go-v2/docs/migrating/

### Final Items to Complete to Mark As Complete

- [x] #41775
- [x] Remove SDK v1 Session and Endpoints (`internal/conns/awsclient.go`)
- [ ] `.ci/scripts/update-aws-sdk-go-dependencies.sh` #42098
- [ ] Skaff data source template (`skaff/datasource/datasourcefw.gtpl`) #42098
- [ ] Docs: `docs/dependency-updates.md` #42098
- [x] ~Test fixtures for CloudFormation~ (`internal/service/cloudformation/test-fixtures/examplecompany-exampleservice-exampleresource`) (not possible, indirect, whole test-fixture needs updating)

### Services Requiring Migration

- [x] #36103 
- [x] #36110
- [x] #36111 
- [x] #36112
- [x] #36113
- [x] #36114
- [x] #36115
- [x] #36116
- [x] #36117
- [x] #36118
- [x] #36119
- [x] #36120
- [x] #36121
- [x] #36122
- [x] #36123
- [x] #36124
- [x] #36125
- [x] #36126
- [x] #36127
- [x] #36128
- [x] #36129
- [x] #36130
- [x] #36131
- [x] #36132
- [x] #36133
- [x] #36134
- [x] #36135
- [x] #36136
- [x] #36137
- [x] #36138
- [x] #36139
- [x] #36140
- [x] #36141
- [x] #36142
- [x] #36143
- [x] #36144
- [x] #36145
- [x] #36146
- [x] #36147
- [x] #36148
- [x] #36149
- [x] #36150
- [x] #36151
- [x] #36152
- [x] #36153
- [x] #36154
- [x] #36155
- [x] #36156
- [x] #36157
- [x] #36158
- [x] #36159
- [x] #36160
- [x] #36161
- [x] #36162
- [x] #36163
- [x] #36164
- [x] #36165
- [x] #36166
- [x] #36167
- [x] #36168
- [x] #36169
- [x] #36170
- [x] #36171
- [x] #36172
- [x] #36173
- [x] #36174
- [x] #36175
- [x] #36176
- [x] #36177
- [x] #36178
- [x] #36179
- [x] #36180
- [x] #36181
- [x] #36182
- [x] #36183
- [x] #36184
- [x] #36185
- [x] #36186
- [x] #36187
- [x] #36188
- [x] #36189
- [x] #36190
- [x] #36191
- [x] #36192
- [x] #36193
- [x] #36194
- [x] #36195
- [x] #36196
- [x] #36197
- [x] #36198
- [x] #36199
- [x] #36200
- [x] #36201
- [x] #36202
- [x] #36203
- [x] #36204
- [x] #36205
- [x] #36206
- [x] #36207
- [x] #36208
- [x] #36209
- [x] #36210
- [x] #36211
- [x] #36212
- [x] #36213
- [x] #36214
- [x] #36215
- [x] #36216
- [x] #36217
- [x] #36218
- [x] #36219
- [x] #36220
- [x] #36221
- [x] #36222
- [x] #36223
- [x] #36224
- [x] #36225
- [x] #36226
- [x] #36227

**Comment by YakDriver** [comment]
Closed with #42098 and (mostly) #41775
