### ISSUE TITLE
Feature Request: AppStream support

### ISSUE THREAD

**Issue by glucas** [hashicorp/terraform-provider-aws#6508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for AppStream resources like fleets, stacks, and image builders. 

These resources are now supported by [CloudFormation](https://aws.amazon.com/about-aws/whats-new/2018/10/introducing-amazon-appstream-2-0-aws-cloudformation-support-and-/)

There are still gaps in AppStream automation -- images must be configured manually -- but being able to create the supported resources via terraform would be a big help.

### New Resources

- [x] aws_appstream_fleet
- [x] aws_appstream_directory_config #21505
- [x] aws_appstream_imagebuilder
- [x] aws_appstream_stack
- [x] aws_appstream_imagebuilder
- [x] aws_appstream_stack_fleet_association #21484
- [x] aws_appstream_stack_user_association #21485
- [x] aws_appstream_user #21485

**Comment by sahil-lakhwani** [comment]
I am interested to work on this.

**Comment by devonbleak** [comment]
Seems like we should also include `aws_appstream_directory_config`

**Comment by UVADave** [comment]
I am using https://github.com/ops-guru/terraform-provider-appstream but it is a little rough around the edges and may not be compatible with terraform 0.12. While we (University of Virginia Library) are only using ApStream for a single application, we have been quite happy with it and expect more adoption... an up to date provider would be great.

**Comment by wrschneider** [comment]
Another plus would be a hypothetical aws_appstream_stack should return the automatically created S3 bucket so you can attach a managed bucket policy via Terraform as well.

**Comment by fred97855** [comment]
Has there been any movement on this? Would be great to see it included in the AWS provider

**Comment by aablake1** [comment]
Has this been added to the aws provider, if so is there any documentation on how to use it?

**Comment by ignatev** [comment]
@ewbankkit Could you please help us with instructions on how to use terraform with appstream?

**Comment by Japeth** [comment]
I can't find any documentation on using appstream with terraform.  Has this actually been added?

**Comment by edg4rgarci4** [comment]
> I can't find any documentation on using appstream with terraform. Has this actually been added?

Any updates?

**Comment by wrschneider** [comment]
I am still interested in this... we have a TF module that creates a stack + fleet + autoscaling groups but has to rely on CloudFormation for the stack/fleet. :-(  it would be a win to have even minimal support in TF for the three resources (stack, fleet, association).

Has anyone made an attempt at a PR yet?

**Comment by wrschneider** [comment]
I started to get the ball rolling #14675, using the ops-guru provider as a starting point.  
I'm not fluent in Go and could use help.

**Comment by wrschneider** [comment]
OK, I now have basic support for a stack and fleet, copied heavily from ops-guru and cleaned up a bit.
It's still rough around the edges but IMO even in its current state it would be better than what I'm doing today.

**Comment by aablake1** [comment]
> OK, I now have basic support for a stack and fleet, copied heavily from ops-guru and cleaned up a bit.
> It's still rough around the edges but IMO even in its current state it would be better than what I'm doing today.
Were you able to update ops-guru's provider to include adding an iam role to an image builder? I tried taking a stab at it but Go isn't a language I'm familiar with. Right now I'm just running some powershell from within terraform to build the image builder instance. The stack and fleet seem ok.

**Comment by wrschneider** [comment]
@aablake1 I wasn't even trying to solve for the image builder.  The stack and fleet are the parts I really need to automate.  In my typical workflow I'm setting up the image builder and creating images by hand in non-production environments, then sharing them.  

What I have in this PR now is the bare minimum I need to replace Cloudformation in my TF for stack/fleet creation.

**Comment by aablake1** [comment]
@wrschneider makes sense. It would be nice if they can add support for AppStream to the main aws terraform provider. Ops-guru provider is better than nothing though so making do with that for now.

**Comment by wrschneider** [comment]
@aablake1  that was the whole point of this issue/my PR, to incorporate into the main AWS TF provider.   If I have to use another TF provider I'm not really that much better off than using CF inside TF.

Now I have all the lint checks passing, at least.

**Comment by arnvid** [comment]
@wrschneider - I am not sure which one of the AppStream providers you used as your source - but we also based ours on ops-guru when we collected the different once into this one https://github.com/arnvid/terraform-provider-appstream currently at v1.0.8  and we are working on a v1.0.9 to work around some problems we found in the provider when updating stack. If you are using the original ops-guru one we have some problems using it in production environments. 

One would hope that Appstream finds it way into the AWS provider - but if does not happen soon I have been thinking of publishing the one I help work on to registry.

**Comment by wrschneider** [comment]
@arnvid  yes I based mine on ops-guru as well.  It seemed like a reasonable start and there were only some minor tweaks I had to make to get it to work.

**Comment by ismailyenigul** [comment]
Hi @arnvid @wrschneider 
Which repo can we use until 15609 and 15610 PR merged?  Can we use https://github.com/arnvid/terraform-provider-appstream in prod? 
@arnvid  Do you have a plan a fix for the following issue in near time? And what is the exact issue you are experiencing when updating stack? 
`we are working on a v1.0.9 to work around some problems we found in the provider when updating stack`

**Comment by flickerfly** [comment]
I see it has been a few months. Have the plans to merge this into the aws provider become any more solid?

**Comment by wrschneider** [comment]
Haven't touched it since then.  Is this even on Hashicorp's backlog?

**Comment by fishdood** [comment]
I came here to make the same comment. This would be really valuable to implement.

**Comment by kodyabbott** [comment]
@breathingdust could we get AppStream added?

**Comment by rednevals** [comment]
I'm in need of this as well...

**Comment by breathingdust** [comment]
Hi all! 👋  AppStream is on the [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md#amazon-appstream) for this quarter:

**Comment by wrschneider** [comment]
> Hi all! 👋 AppStream is on the [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md#amazon-appstream) for this quarter:

Yay!  @breathingdust Let me know how I can help

**Comment by liberops** [comment]
Is there a way to associate an Appstream stack with an Appstream fleet with Terraform?
Thanks

**Comment by rednevals** [comment]
> Is there a way to associate an Appstream stack with an Appstream fleet with Terraform? Thanks

Yup!
```
resource "appstream_stack_attachment" "stack_fleet_association" {
  appstream_stack_id = appstream_stack.rndc_stack.name
  appstream_fleet_id = appstream_fleet.rndc_fleet.name
}
```

**Comment by etiennejeanneau** [comment]
First off, thanks for the work on this!
It seems AssociateFleet https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.AssociateFleet is missing on the roadmap to glue the stack and fleet together. I'm unsure if it has been missed  in the official hashicorp roadmap.
*DirectoryConfig would be nice too ;)

**Comment by mbotmcc** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/21718 is a bit of an issue for us as we use desktop mode

**Comment by Arisfx** [comment]
Hi team, great work on this! i cant find the terraform code for `image registry`- am i missing something?

**Comment by breathingdust** [comment]
Closing this issue as the originally scoped work has been completed. Created a separate issue to track `aws_appstream_image` in #22536
